### ISSUE TITLE
[adapter-node-http] headers are string arrays

### ISSUE THREAD

**Issue by feinoujc** [Netflix/pollyjs#174]
I noticed the the request headers are string arrays when using the adapter-node-http, which is different than the other adapters (fetch). Was this intentional? Could see an argument either way, but it would be nice if the `Request` abstraction could smooth over differences between adapters

```js
polly.server.post('/endpoint').on('request', req => {
   // this is a string array
   const header = req.headers['accept-language'];
});
```

**Comment by offirgolan** [comment]
@feinoujc the headers were intensionally left as-is and not normalized since node treats array values a bit differently (see [here](https://nodejs.org/api/http.html#http_request_setheader_name_value)).

```js
req.setHeader('foo', 'a, b, c');

/* 
  Output: 
  
  Foo: a, b, c
*/
```

```js
req.setHeader('foo', ['a', 'b', 'c']);

/* 
  Output: 
  
  Foo: a
  Foo: b
  Foo: c
*/
```

If all the header values are arrays, including single values, we can normalize that a bit so it's just a single string. Let me know if that's the case here.

**Comment by feinoujc** [comment]
as long as it was intentional, I understand the reasoning 👍
