### ISSUE TITLE
Always makes unwanted http requests to API, instead of using existing recording

### ISSUE THREAD

**Issue by shankarsridhar** [Netflix/pollyjs#192]
When I rerun acceptance tests, my recordings are updated every time. It seems to me like the `expiresIn` option is not working. Am I missing anything obvious here w.r.t adding the config ?

I am using the `"@pollyjs/ember"` version `2.3.1` ember addon to use pollyjs in my ember app.

I have the following config entry in my `ember-cli-build.js`
```js
pollyjs: {
      enabled: EmberApp.env() !== 'production',
      expiresIn: '30d5h10m',
      server: {
        expiresIn: '30d5h10m',
        keepUnusedRequests: false
      }
    }
```

Entry from `package.json`:
```json
{
...
  "@pollyjs/ember": "^2.3.1",
...
}
```

## Environment
```
Node.js v10.15.0
darwin 18.2.0
ember-cli: 3.7.0
node: 10.15.0
os: darwin x64
```

**Comment by offirgolan** [comment]
@shankarsridhar do the request id's change from each run of the acceptance tests? The ids can be found in the recorded har file under `entries[{ _id: '1234abcd'}]`. If not, try removing the `expiresIn` config option. If that fixes it, then I can try to figure out why `expiresIn` is not working as expected.

**Comment by shankarsridhar** [comment]
@offirgolan, Thanks for the suggestion.
New Object gets created under `log.entries` array, every time I rerun my acceptance test. I removed the `expiresIn` config option. But still I'm seeing the same issue.

**Comment by offirgolan** [comment]
@shankarsridhar the configuration options you've set in the `ember-cli-build.js` file are for the configuration of the addon itself as well as the express server middleware that we attach. Instead you want to add the configuration option when calling [setupPolly](https://netflix.github.io/pollyjs/#/test-frameworks/qunit).

```js
setupPolly(hooks, { expiresIn: '10days' })
```

> New Object gets created under log.entries array, every time I rerun my acceptance test. I removed the expiresIn config option. But still I'm seeing the same issue.

This might be due to having some dynamic headers like dates or uuids that are different everytime you run your tests. You would need to mess around with the [matchRequestsBy](https://netflix.github.io/pollyjs/#/configuration?id=matchrequestsby) config.

**Comment by shankarsridhar** [comment]
Thanks @offirgolan I played around with the config option to `setupPolly`and I was able to get it working like I wanted.

In case you are curious, this was the config that worked for me:
```
setupPolly(hooks, {
    mode: 'replay',
    expiresIn: '30days',
    matchRequestsBy: {
      headers: false,
      url: {
        pathname: false,
        query: false,
        hash: false
      }
    }
  });
```

**Comment by offirgolan** [comment]
Np! Glad it worked out 😄
