### ISSUE TITLE
How do you debug why a request wasn't replayed?

### ISSUE THREAD

**Issue by sdegutis** [Netflix/pollyjs#215]
The issue:

When I replay a request that I know I've recorded, it's not found.

To debug it, I've done this:

1. Pass `logging: true` into the constructor.
2. Look in the console and found that a request is called "Recorded" when it should have said "Replayed".
3. Looked into the request's JavaScript properties to see if there was anything special about it that I didn't already see in the Network inspector panel's Request Headers section. Nope, nothing stands out as useful information.
4. Checked in `JSON.parse(localStorage.pollyjs)` for recorded requests matching the one I know I recorded and called `polly.persister.persist()` after. It doesn't seem to be there.

None of these have helped me track down why the request doesn't seem to be persisted in localStorage, or if I'm even correct in assuming that's the root cause here.

How is this kind of debugging of a non-replayed request typically done with Polly.JS?

Thanks in advance for your guidance on this issue.

**Comment by offirgolan** [comment]
@sdegutis most of the time the reason for requests not being correctly matched is due to some header key/value pair that is unique to that specific request. To find out what request attributes are used to generate the ID for the request, in the console, look for the `identifiers` object on the request instance. I would do a diff on these identifiers to see what has changed between each run.

**Comment by sdegutis** [comment]
Thanks.

**Comment by vjpr** [comment]
Would be nice to have a flag that does a diff against all requests in the `har`.

**Comment by Josiassejod1** [comment]
> Would be nice to have a flag that does a diff against all requests in the `har`.
> 
> 
> 
> I managed to implement something for myself...if anyone is interested I can clean up and post it.

You got this ???
