### ISSUE TITLE
monitoring http request/response over kubernetes cluster

### ISSUE THREAD

**Issue by niztal** [Netflix/pollyjs#280]
Hi all,

Is there a way I can record HTTP requests/responses over a k8s cluster?

Assuming I would like to monitor all traffic among/outside of pods within k8s cluster, is there a way doing so via polly.js?

Thanks.

**Comment by jasonmit** [comment]
Polly is for recording and replaying supported adapters: xhr, fetch, and node's http module.  Polly needs to be running within a node application or browser bundle in order to record/replay.  I don't see how this would be compatible with observing all traffic in a kubernetes cluster unless it's instantiated within all the apps running within the cluster.
