### ISSUE TITLE
Polly should use standard HAR `encoding` property with Base64, not non-standard `_isBinary` with hex content (4x the size)

### ISSUE THREAD

**Issue by felixfbecker** [Netflix/pollyjs#371]
## Description

Polly's support for binary contents (e.g. images) currently works by writing `_isBinary: true` into the HAR and encoding the body in hexadecimal. Polly uses this as an internal representation too, which is a bit weird since internally the content can just be a much more efficient `Buffer`.

This is non-standard. It means that a HAR from Polly is not interoperatable with other tools like Chrome dev tools, e.g. it is impossible to load a Polly HAR in Chrome because Chrome will treat the hex content as a literal string.

Hexadecimal encoding is also extremely large - 4x (300%!) as Base64, and Base64 is already 37% larger than binary. Polly HARs are committed to Git, so this is a problem even much larger than committing raw binary into Git repositories (increased clone time that can never be reduced again).

There is a standard in HAR to encode binary files, [the `encoding` field](https://w3c.github.io/web-performance/specs/HAR/Overview.html#content:~:text=encoding%20%5Bstring%2C%20optional%5D%20(new%20in%201.2),its%20original%20character%20set%20into%20UTF%2D8):

> encoding [string, optional] (new in 1.2) - Encoding used for response text field e.g "base64". Leave out this field if the text field is HTTP decoded (decompressed & unchunked), than trans-coded from its original character set into UTF-8.

This can be set to `base64` to treat the content as Base64, which would be interoperatable with other tools and 1/4th of the size of hexadecimal encoding.

**Comment by jasonmit** [comment]
@felixfbecker binary support was added as an after thought to Polly and worked on by a few people, so HAR interop with binary content was likely overlooked.  It seems you have a good bit of knowledge in this area, let us know if you're interested in correcting this behavior.

**Comment by offirgolan** [comment]
This can be split up into 2 separate issues. The first is replacing `_isBinary` with `encoding` and the 2nd is using `base64` encoding rather than `hex`. 

The latter might not be as simple since we don't just store `hex`, we also store a json stringified array of hex chunks for the node adapter since those need to be replayed back to the stream chunk by chunk. We could however still replace the hex values with base64 but that would still make the HAR encoding not fully base64 which could be problematic. We're open to suggestions on how to correctly store these chunks correctly. 

I've been incredibly swamped with work so a PR would be welcomed 😄

**Comment by renanvalentin** [comment]
Hello! (Not sure if this is the right place to ask) 

I'm trying to re-use the HAR content to spin up another task. How can you decode the array of hex chunks into json?  

Thanks!

**Comment by roschaefer** [comment]
> Hello! (Not sure if this is the right place to ask)
> 
> I'm trying to re-use the HAR content to spin up another task. How can you decode the array of hex chunks into json?
> 
> Thanks!

Hey @renanvalentin better late than never. I had the same problem like you and here's my implementation to decode/encode the binary encoded response body for `@pollyjs/adapter-node-http@^5.1.1`:

```ts
import { gzip, ungzip } from 'node-gzip'
import { RecordingEventListener } from '@pollyjs/core'

type Filter = (json: Record<string, unknown>) => Record<string, unknown>

type Recording = {
  response: { content: { text: string; _isBinary: boolean } }
  request: { headers: unknown[]; postData: { text: string } }
}

const decodeBinary = async (text: string) => {
  const body = JSON.parse(text)
  const buffer = Buffer.concat(
    body.map((chunk: string) => Buffer.from(chunk, 'hex'))
  )
  const unzipped = await ungzip(buffer)
  return unzipped.toString()
}

const encodeBinary = async (text: string) => {
  const zipped = await gzip(text)
  return JSON.stringify([zipped.toString('hex')])
}

const filterReponseBody = (filter: Filter) => (text: string) => {
  try {
    return JSON.stringify(filter(JSON.parse(text)))
  } catch (error) {
    if (error instanceof SyntaxError) return text // filter HTML maybe?
    throw error
  }
}

const filterResponse = async (recording: Recording) => {
  const filter: Filter = // TODO: add your custom filter implementation
  const filterBody = filterReponseBody(filter)
  const {
    response: { content },
  } = recording
  if (content._isBinary) {
    const text = await decodeBinary(content.text)
    const filtered = filterBody(text)
    content.text = await encodeBinary(filtered)
  } else {
    content.text = filterBody(content.text)
  }
}

export const filterSensitiveData: RecordingEventListener = async (
  _request,
  recording
) => {
  // filterRequest(recording)
  await filterResponse(recording)
}
```

The `filterSensitiveData` gets plugged into `beforePersist` hook: https://netflix.github.io/pollyjs/#/server/events-and-middleware?id=beforepersist

This implementation will break as soon as the team releases another version of `@pollyjs/adapter-node-http` as requested by me here: https://github.com/Netflix/pollyjs/pull/420#issuecomment-1030291423


@offirgolan @jasonmit why is it so difficult to parse the binary response body? Should this be a feature request to PollyJS?

**Comment by offirgolan** [comment]
Unfortunately its not very straightforward at the moment but I agree it would be nice to expose some public-facing utils to handle this. 

As of right now, you can leverage the code we use to do this here:

https://github.com/Netflix/pollyjs/blob/18262cf3213d3f3ca7a778a574c162dc2318860a/packages/%40pollyjs/adapter-node-http/src/index.js#L280-L336

Once you get the chunks of binary content, you can either decompress them directly or create a stream and read it however you'd like.

**Comment by roschaefer** [comment]
Thanks @offirgolan I was looking at this very file in order to come up with my implementation. My preferred API would be proper typings on the `recordings` argument of the `beforePersist` callback and a getter/setter for the response body. The `recording` would then be responsible to save the given (updated) object as either `base64` or `uft8`. It should not be the job of the calling code to encode/decode the response body.

I don't really understand the rationale why we apply a combination of `JSON.stringify`, String Buffer encoded as `base64` sometimes split into chunks followed by `gzip`. For the time being I'm happy that my code :point_up: still works after the update to `6.0.4` by replacing `hex` with `base64` and `_isBinary` with `encoding`.

My use case is to filter sensitive data coming back from a HTTP response. What are the current alternatives? I saw already encrypting/decrypting the whole thing in `beforePersist`, `beforeReplay` and using a REST persister, so the files are not checked into version control. I'm not very happy with these solutions because of complexity.
