### ISSUE TITLE
Parallel tests support in Polly?

### ISSUE THREAD

**Issue by patrickshaughnessy** [Netflix/pollyjs#375]
## Description

Does Polly support parallel test runs, particularly for the node-http-adapter setup?

I have a node server set up with Polly, which is used by my Cypress tests. Everything works fine running the Cypress tests in series. Running tests in parallel doesn't seem to be supported though.

Here's an example:
1. Test A & B kicked off in parallel, polly mode = REPLAY (Both recorded previously, and individual or serial replay run works fine)
2. Test A starts sending requests to the node server with header "recording-name=TestA".
3. Node server receives request, sets up the polly instance to replay recordings for TestA.
4. In parallel, Test B starts sending requests to the node server with header "recording-name=TestB"

In this example, I'd expect to be able to tell Polly that for node requests with header "recording-name=TestA", use TestA recordings. While for header "recording-name=TestB", use TestB recordings.

Some ideas I've tried include:
-  Spinning up multiple polly instances per test (fails because only one node-http-adapter can be active at a time)
- Using the `polly.server.on('request')` and `overrideRecordingName` methods to try and force the recording name before Polly tries to retrieve it.

Neither option seems to work and I'm suspecting the Polly doesn't support this kind of use case at the moment, but would like to confirm if I'm doing something wrong.

### Shareable Source

```js
// Attempted idea:

		polly.server
			.any()
			.filter(_req => {
				// Recording name is configured on the new Polly() call
				// https://netflix.github.io/pollyjs/#/server/request?id=recordingname
				return _req.recordingName !== testName;
			})
			.on('request', _req => {
				console.log('\n\n override recording name', testName);
				// Override the recordingName whenever it's different from the original config
				// https://netflix.github.io/pollyjs/#/server/request?id=overriderecordingname
				_req.overrideRecordingName(testName);
			});
```

### Error Message & Stack Trace

N/A

### Config

N/A

### Dependencies

Copy the @pollyjs dependencies from `package.json`:

```json
{
		"@pollyjs/adapter-node-http": "^5.1.0",
		"@pollyjs/core": "^5.1.0",
		"@pollyjs/persister-fs": "^5.0.0",
}
```

## Relevant Links

- Project is not public

## Environment
Node.js v12.18.4
darwin 18.7.0
6.14.6

**Comment by guyellis** [comment]
I've never used Cypress before so some of what follows might be inaccurate as I'm guessing here.

Looking at [the docs](https://docs.cypress.io/guides/guides/parallelization.html#Overview) it says:

> Cypress can run recorded tests in parallel across multiple machines since version 3.1.0. While parallel tests can also technically run on a single machine, we do not recommend it since this machine would require significant resources to run your tests efficiently.

I'm running parallel tests with PollyJS on a single machine (8 core - 7 parallel tests at a time) but I'm using Jest. Jest creates a separate worker per test that's running which I believe is giving PollyJS and all other dependencies and servers that I spin up the isolation that they need. If that isolation is not "naturally" provided by the Worker isolation then you can use the JEST_WORKER_ID (unique per test suite) to force/allow your resource to not clash with other tests. For example this ID can ensure that a unique port is used per server that you spin up.

So for your Cypress parallel tests can this clash that you're experiencing be prevented by somehow configuring PollyJS in a manner that is unique per tests suite instance like it can with Jest? i.e. does Cypress provide a similar environment to uniquely identify the test suite that's running.

Also, diving into why the Cypress docs don't recommend running in parallel on the same machine might reveal why this issue is happening. If, as the quoted text above says "...since this machine would require significant resources..." is the only reason then this research is not necessary.

**Comment by patrickshaughnessy** [comment]
@guyellis Thanks for the response! There are a couple issues at play here, and I'll try to clarify the situation as best I can.

There are 3 git repos involved:
1. The server repo which contains the node JS server application
2. The client repo which contains static assets (React app and related code) pushed to a CDN
3. The E2E test repo which contains E2E tests for many projects

To effectively mock E2E tests, I'm trying to set up Polly on both the node server (1) and the E2E test (3). Setting up on:
- the node server in order to mock downstream API calls (but still test the node server code itself during E2E runs)
- the E2E test in order to mock test dependency calls like creating a user, which uses an internal service to interface with the DB (but still test the client side assets and code)

A key point here that differs from your description is that our E2E tests do not spin up the node server. The server and client assets are decoupled for independent deployments. The server is already up and running on a stage environment when the E2E test is run.

Ignoring any limitations with Cypress for a moment, the problem really comes from trying to use Polly on the node server. The new Polly instance must be created with a test name. That's fine - I've configured the node server to create the new Polly instance if none exists when a request comes in with the special test name header value (this would be a request from the React app to the node server). This Polly instance must be assigned to a global in the node file scope. It cannot be assigned to the request object or similar ephemeral scope because the E2E test usually spans more than one request to the node server. This Polly instances starts replaying all the downstream API requests against the given test name (assume I've already recorded test runs individually).

But if tests are running in parallel, now requests are coming in with different test name headers. There is already a Polly instance from the first request to come in, and creating multiple instances is not possible because only a single node-http-adapter can be active (I think because the Polly setup patches into the global http request or something similar). So I'm unable to get the existing Polly instance to serve the correct replay for the test.

The node server doesn't mind multiple parallel requests. The Polly instance ties the node-http-adapter to a single test name though, which I think is the crux of the problem.

I think to have parallel test support with this setup, there would need to be a way for Polly to index recordings by test name, so that a single Polly instance (with a single node-http-adapter) could intercept all concurrent requests on the node server and grab the correct recording by test name.

**Comment by guyellis** [comment]
In a similar architecture to what you've just described we setup the dependency services as a single mock server that always returns the same response/payload based on the pattern of the requests.

So that mock server is an actual NodeJS service with Hapi as its routing engine and is able to act at the upstream services for all dependencies of the services that we need consistent results back from.

Now we haven't tried this but I'm wondering if you could record `.har` files in that mock server and have those played back for each request pattern? That was so long as the pattern (headers + url + other) is unique you should be able to have PollyJS respond with the appropriate `.har` file.

**Comment by patrickshaughnessy** [comment]
@guyellis Yes that's exactly the idea and set up we have. However, in practice this doesn't actually work with parallel tests (with serial tests, it's fine). PollyJS records the `.har` against a test name, so once the Polly instance is set up on the NodeJS service, it serves the mocks only from that test name `.har`.  There doesn't seem to be a good way to tell Polly, "for this request, serve these `.har` mocks, but for that request, serve these other `.har` mocks" when running tests against that NodeJS server in parallel.

**Comment by offirgolan** [comment]
From reading through this issue, it sounds like you have a single Polly instance that is trying to orchestrate which recordings to play based on the recording name header of the request. 

Based on that, have you tried doing something like this:

```js
polly.server
			.any()
			.filter(req => {
				// Handle only requests with the a recording name header
				return req.hasHeader('recording-name')
			})
			.on('request', req => {
				// Override the recording name to that of the recording name header
				req.overrideRecordingName(req.getHeader('recording-name'));
			});
```

**Comment by patrickshaughnessy** [comment]
Hi @offirgolan - yes that is my setup and thanks for the suggestion. I have tried this exact idea. Unfortunately it doesn't quite work, and I think here's why:

On the `.filter()`, PollyJS is looking at requests **outgoing from the NodeJS server**. E.g. From my NodeJS server to Transactions Service API. These requests do not have any special header (otherwise I'd have to add it to each service request throughout the node app - not practical). The recording name header is on the request **incoming to the NodeJS server**. E.g. From my React app to the NodeJS server. (Actually this is flowing in via cookies, but same idea).

One thing that I can do is for each request incoming to the NodeJS server, set a recordingName property on the Express `req` object. From PollyJS then, I'd need a way to access that property via closure at the time of creating / handling the PollyJS request intercept (specifically of looking up of the recording). Maybe something like: https://github.com/Netflix/pollyjs/compare/master...patrickshaughnessy:parallel_support?expand=1#diff-2556cd1f63bf685652aba90f39b34ddf64114b19d78ecee55cc2d6ad9744030dR49

I'm not familiar enough yet with the PollyJS codebase to know if that's a viable option, or if such an option already exists though. I was originally hopefully that `overrideRecordingName` was the ticket, but I haven't been able to get that working like I thought it would.

**Comment by offirgolan** [comment]
Hmm, let me see if I understand this correctly:

1. Your cypress test makes a request to the Node app with a recording-name header
2. Your node app then passthroughs that request to the Service API and records it to the given header
3. Your node app then replays that request for the given header on the subsequent execution

Have you tried hooking up Polly to the cypress instance instead? Here is a quick [example](https://gist.github.com/skimi/07a721316e9593d5cb248c1e54538c58). You should also be able to use the FS persister (instead of the REST one in the example). You can also hook up to XHR the same way that the fetch adapter is being setup.

**Comment by patrickshaughnessy** [comment]
Yes that's correct. And it all works fine for tests running serially BTW. It's just running tests in parallel that I'm not able to get working.

Actually there is Polly hooked up to the cypress instance as well (to capture test framework calls like user creation and modification). These calls would hit the stage environment DBs in regular FT runs like for release testing (testing against the actual services). We don't want to mock the XHR calls between our React app and NodeJS Server, because that's the system under test - both the React app and NodeJS server together.

**Comment by patrickshaughnessy** [comment]
@offirgolan @guyellis Thanks for the inputs. I think I may have missed something in my own understanding. The requests from the NodeJS App to the Service APIs will also still need the test name header, because the http interceptor is just looking at the properties of the http request itself, with no context anywhere of the Express request object. For some reason I was thinking Polly could somehow get this Express request context during the intercept, but that's not really possible.

I will try updating the implementation of the Service API calls to add this context, and then using the `overrideRecordingName` feature during the request replay.

**Comment by patrickshaughnessy** [comment]
That worked great. Thanks for the inputs and guidance!
