### ISSUE TITLE
Tests using Polly freeze when in CI mode

### ISSUE THREAD

**Issue by Turbo87** [Netflix/pollyjs#8]
Using `ember test` the tests using Polly freeze, when using `ember test --server` it seems to work fine 🤔 

Reproduction currently available at https://github.com/skylines-project/skylines/pull/918

**Comment by offirgolan** [comment]
I tracked this down to `ember-cli-pace` injecting a global XHR override into the tests/index.html. I suggest disabling it in test or opening an issue with the addon author to override the `XMLHttpRequest.prototype.send` method instead of the global class.

@Turbo87 I'm gonna go ahead a close this issue. Feel free to reopen!
